module aqua_tests include("aqua.jl") end
module wolf_artr_tests include("wolf_artr.jl") end
module artifacts_tests include("artifacts.jl") end
module truncated_normal_tests include("truncated_normal.jl") end
module io_tests include("io.jl") end
module hmm_tests include("hmm.jl") end
module elife2020_tests include("elife2020.jl") end
module atol_tests include("ATol.jl") end
module util_tests include("util.jl") end
