name = "ZebrafishHMM2023"
uuid = "982e605e-fd7d-4c5d-a517-224ed2053a87"
authors = ["JFdCD <jfdecd@icloud.com>"]
version = "1.0.0-DEV"

[deps]
HiddenMarkovModels = "84ca31d5-effc-45e0-bfda-5a68cd981f47"

[compat]
HiddenMarkovModels = "0.2"
julia = "1.9"
