name: CI
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
        os:
          - ubuntu-latest
        arch:
          - x64
    env:
      GH_TOKEN: ${{ secrets.KAKI_PAT }}
      JULIA_PKG_USE_CLI_GIT: true
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: julia-actions/setup-julia@5c9647d97b78a5debe5164e9eec09d653d29bd71
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@824243901fb567ccb490b0d0e2483ccecde46834
      - run: julia --color=yes --project=.ci/ -e 'import Pkg; Pkg.Registry.add(Pkg.RegistrySpec(url="https://github.com/cossio/CossioJuliaRegistry.git"))'
      - run: gh auth setup-git
      - uses: julia-actions/julia-buildpkg@e3eb439fad4f9aba7da2667e7510e4a46ebc46e1
      - uses: julia-actions/julia-runtest@1e03e0122a598a569004c1e26950e2547b350ec0
